def test_imports():
    import ctrader.analytics
    import ctrader.cli.trade
    import ctrader.config_loader
    import ctrader.data_providers.coinspot
    import ctrader.data_providers.coinspot_v2
    import ctrader.data_providers.marketdata
    import ctrader.execution.coinspot_execution
    import ctrader.execution.paper
    import ctrader.notify
    import ctrader.portfolio
    import ctrader.risk.risk_manager
    import ctrader.strategies.inverse_vol
    import ctrader.strategies.momentum
    import ctrader.strategies.trend_filter
