name: Bug report
description: Create a report to help us improve
title: "[BUG] "
labels: ["bug"]
body:
  - type: textarea
    attributes: { label: What happened?, description: Steps to reproduce }
    validations: { required: true }
