name: lint-ci
on:
  pull_request:
  push:
    branches: [ main ]
permissions:
  contents: read
defaults:
  run:
    shell: bash
jobs:
  black:
    name: black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install --upgrade pip pre-commit
      - run: pre-commit run black --all-files
  ruff:
    name: ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install --upgrade pip pre-commit
      - run: pre-commit run ruff --all-files
  ruff-format:
    name: ruff-format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install --upgrade pip pre-commit
      - run: pre-commit run ruff-format --all-files
  isort:
    name: isort
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install --upgrade pip pre-commit
      - run: pre-commit run isort --all-files
  detect-secrets:
    name: detect-secrets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install --upgrade pip pre-commit
      - run: pre-commit run detect-secrets --all-files
